ARDUINO_DIR = /home/ildus/Arduino/arduino-1.6.12

BOARD_TAG    = mini
BOARD_SUB    = atmega328
ARDUINO_LIBS = Wire LiquidCrystal_I2C1602V1 VolumeBar
ARDUINO_SKETCHBOOK = ${ARDUINO_DIR}
CXXFLAGS_STD      = -std=gnu++11

include /usr/share/arduino/Arduino.mk
